import { Router } from 'express';
import { login, me, register } from '../modules/auth/auth.controller.js';
import { requireAuth, requireRole } from '../middleware/auth.js';
import { listMovies, getMovie } from '../modules/movies/movie.controller.js';
import { lockSeats, createBooking, myBookings, validateTicket } from '../modules/bookings/booking.controller.js';
import { listFood } from '../modules/food/food.controller.js';
import { dashboard } from '../modules/admin/admin.controller.js';
import { upload } from '../services/uploadService.js';
export const router = Router();
router.get('/health', (_req, res) => res.json({ ok: true, service: 'movie-hub-api' }));
router.post('/auth/register', register);
router.post('/auth/login', login);
router.get('/auth/me', requireAuth, me);
router.get('/movies', listMovies);
router.get('/movies/:id', getMovie);
router.get('/food', listFood);
router.post('/bookings/lock', requireAuth, lockSeats);
router.post('/bookings', requireAuth, createBooking);
router.get('/bookings/me', requireAuth, myBookings);
router.post('/tickets/validate', requireAuth, requireRole('SUPER_ADMIN','CINEMA_ADMIN','STAFF'), validateTicket);
router.get('/admin/dashboard', requireAuth, requireRole('SUPER_ADMIN','CINEMA_ADMIN','STAFF'), dashboard);
router.post('/admin/uploads', requireAuth, requireRole('SUPER_ADMIN','CINEMA_ADMIN'), upload.single('asset'), (req, res) => res.status(201).json({ file: req.file }));
