import type { ReactNode } from 'react';
import { BarChart, Bar, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis, LineChart, Line } from 'recharts';
import { Film, Popcorn, Ticket, Users } from 'lucide-react';
import { movies } from '../data';
const revenue=[{d:'Mon',v:12000},{d:'Tue',v:18000},{d:'Wed',v:15000},{d:'Thu',v:26000},{d:'Fri',v:42000},{d:'Sat',v:51000},{d:'Sun',v:39000}];
const occ=[{name:'Booked',value:72},{name:'Open',value:28}];
export function AdminDashboard(){return <div className="space-y-6"><Header title="Command Center" sub="Realtime operations for Lite Cinema"/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Ticket} k="Total bookings" v="18,420"/><Metric icon={Film} k="Today shows" v="126"/><Metric icon={Popcorn} k="Food sales" v="$12.8k"/><Metric icon={Users} k="Occupancy" v="72%"/></div><div className="grid gap-5 xl:grid-cols-[1fr_360px]"><Panel title="Revenue summary"><ResponsiveContainer width="100%" height={300}><LineChart data={revenue}><CartesianGrid stroke="rgba(255,255,255,.08)"/><XAxis dataKey="d" stroke="#B3B3B3"/><YAxis stroke="#B3B3B3"/><Tooltip contentStyle={{background:'#121212',border:'1px solid rgba(255,122,0,.25)'}}/><Line type="monotone" dataKey="v" stroke="#FF7A00" strokeWidth={4}/></LineChart></ResponsiveContainer></Panel><Panel title="Occupancy"><ResponsiveContainer width="100%" height={300}><PieChart><Pie data={occ} dataKey="value" innerRadius={70} outerRadius={110}>{occ.map((_,i)=><Cell key={i} fill={i?'#412302':'#FF7A00'}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></Panel></div><Panel title="Recent bookings"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-muted"><tr><th className="p-3">Booking</th><th>Customer</th><th>Movie</th><th>Status</th><th>Total</th></tr></thead><tbody>{['BK45','BK62','BK88'].map((id,i)=><tr className="border-t border-white/10" key={id}><td className="p-3 font-bold text-ember">{id}</td><td>Ahmed Nabil</td><td>{movies[i%movies.length].title}</td><td><span className="rounded-full bg-green-500/15 px-3 py-1 text-green-300">CONFIRMED</span></td><td>$72.00</td></tr>)}</tbody></table></div></Panel></div>}
export function AdminMovies(){return <div><Header title="Movie Management" sub="Add, publish, upload posters, and schedule content"/><div className="mt-6 grid gap-4 md:grid-cols-3">{movies.map(m=><div className="glass rounded-[28px] p-4" key={m.id}><img src={m.poster} className="h-56 w-full rounded-2xl object-cover"/><h3 className="mt-3 font-bold">{m.title}</h3><p className="text-sm text-muted">{m.genre}</p><div className="mt-3 flex gap-2"><button className="rounded-xl bg-ember-gradient px-3 py-2 text-sm">Edit</button><button className="rounded-xl border border-white/10 px-3 py-2 text-sm">Unpublish</button></div></div>)}</div></div>}
export function AdminShows(){return <div><Header title="Show Management" sub="Create showtimes, cancel or reschedule shows, manage availability"/><Panel title="Weekly show volume"><ResponsiveContainer width="100%" height={320}><BarChart data={revenue}><CartesianGrid stroke="rgba(255,255,255,.08)"/><XAxis dataKey="d" stroke="#B3B3B3"/><YAxis stroke="#B3B3B3"/><Tooltip contentStyle={{background:'#121212'}}/><Bar dataKey="v" fill="#FF7A00" radius={[12,12,0,0]}/></BarChart></ResponsiveContainer></Panel></div>}
export function AdminSettings(){const fields=['Site name','Theme color','Currency','Tax percentage','Booking timeout','Cancellation rules','Contact details','Social links'];return <div><Header title="Settings & CMS" sub="Every frontend content block can be edited from here"/><div className="mt-6 grid gap-3 md:grid-cols-2">{fields.map(f=><label className="glass rounded-2xl p-4" key={f}><span className="text-sm text-muted">{f}</span><input className="mt-2 w-full bg-transparent font-semibold outline-none" defaultValue={f==='Site name'?'Movie Hub / Lite Cinema':''}/></label>)}</div></div>}
function Header({title,sub}:{title:string;sub:string}){return <div><p className="text-ember">Admin panel</p><h1 className="text-4xl font-bold">{title}</h1><p className="mt-2 text-muted">{sub}</p></div>}
function Metric({icon:Icon,k,v}:any){return <div className="glass rounded-[28px] p-5"><Icon className="text-ember"/><p className="mt-4 text-sm text-muted">{k}</p><b className="text-3xl">{v}</b></div>}
function Panel({title,children}:{title:string;children: ReactNode}){return <section className="glass rounded-[32px] p-5"><h2 className="mb-4 text-xl font-bold">{title}</h2>{children}</section>}
