import { useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ShieldCheck } from 'lucide-react';
import { SeatMap } from '../components/SeatMap';
import { cinemas, movies, seats, shows } from '../data';
import type { Seat } from '../types/domain';
import { money } from '../utils/format';
export function BookingPage(){const {movieId}=useParams();const movie=movies.find(m=>m.id===movieId)??movies[0];const show=shows.find(s=>s.movieId===movie.id)??shows[0];const cinema=cinemas.find(c=>c.id===show.cinemaId)!;const [selected,setSelected]=useState<string[]>(['A5','C6','F7']);const total=useMemo(()=>seats.filter(s=>selected.includes(s.id)).reduce((a,s)=>a+s.price,0),[selected]);function toggle(seat:Seat){setSelected(v=>v.includes(seat.id)?v.filter(id=>id!==seat.id):[...v,seat.id])}return <div className="mx-auto max-w-3xl py-6"><div className="mb-5 flex items-center justify-between"><div><p className="text-muted">{cinema.name}</p><h1 className="text-2xl font-bold">{movie.title}</h1></div><Link to="/movies/dune-2" className="rounded-full bg-white/10 px-3 py-2">♡</Link></div><SeatMap seats={seats} selected={selected} onToggle={toggle}/><div className="mt-7 space-y-5"><Pick title="Select Date" items={['Sat 23 May','Sun 24 May','Mon 25 May','Tue 26 May']}/><Pick title="Select Time" items={['7:50 PM','10:20 PM','12:30 PM']}/><div className="glass flex items-center justify-between rounded-[28px] p-5"><div><p className="text-sm text-muted">{show.hall} • Seats</p><h2 className="text-xl font-bold">{selected.join(', ') || 'Choose seats'}</h2><p className="text-sm text-muted">({selected.length} Tickets)</p></div><div className="text-right"><p className="text-xs text-muted">Total Price</p><b className="text-2xl text-ember">{money(total)}</b></div></div><Link to="/checkout" className="block rounded-2xl bg-ember-gradient px-6 py-4 text-center font-bold shadow-glow">Book Now</Link><p className="flex items-center justify-center gap-2 text-xs text-muted"><ShieldCheck size={14} className="text-ember"/> Your booking is safe and secure</p></div></div>}
function Pick({title,items}:{title:string;items:string[]}){const [active,setActive]=useState(items[0]);return <div><h3 className="mb-3 font-semibold">{title}</h3><div className="flex gap-2 overflow-x-auto">{items.map(i=><button onClick={()=>setActive(i)} className={`shrink-0 rounded-2xl px-4 py-3 text-sm ${active===i?'bg-ember-gradient':'glass text-muted'}`} key={i}>{i}</button>)}</div></div>}
