import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Check, CreditCard, Plus, Shield, Wifi } from 'lucide-react';
import { TicketCard } from '../components/TicketCard';
import { demoBooking, food } from '../data';
import { money } from '../utils/format';
export function CheckoutPage(){const [addons,setAddons]=useState<string[]>(['combo-1']);const foodTotal=food.filter(f=>addons.includes(f.id)).reduce((a,f)=>a+f.price,0);const tax=(demoBooking.total+foodTotal)*.14;const total=demoBooking.total+foodTotal+tax;return <div className="mx-auto grid max-w-6xl gap-6 py-8 lg:grid-cols-[1fr_380px]"><section className="space-y-5"><h1 className="text-3xl font-bold">Checkout</h1><div className="glass rounded-[32px] p-5"><h2 className="font-bold">Payment method</h2><div className="mt-4 space-y-3"><Card brand="VISA" last="4242" active/><Card brand="mastercard" last="0338"/><button className="w-full rounded-2xl border border-dashed border-ember/50 py-4 text-ember"><Plus className="inline"/> Add New Card</button></div><p className="mt-4 flex gap-2 rounded-2xl bg-white/5 p-3 text-sm text-muted"><Shield className="text-ember"/> Industry-standard encryption protects every transaction.</p></div><div className="glass rounded-[32px] p-5"><h2 className="font-bold">Food add-ons</h2><div className="mt-4 grid gap-3 sm:grid-cols-3">{food.map(f=><button key={f.id} onClick={()=>setAddons(v=>v.includes(f.id)?v.filter(id=>id!==f.id):[...v,f.id])} className={`overflow-hidden rounded-3xl border text-left ${addons.includes(f.id)?'border-ember bg-ember/10':'border-white/10 bg-white/5'}`}><img src={f.image} className="h-28 w-full object-cover"/><div className="p-3"><b>{f.name}</b><p className="text-sm text-muted">{f.stock} in stock</p><p className="text-ember">{money(f.price)}</p></div></button>)}</div></div></section><aside className="glass h-fit rounded-[32px] p-5"><h2 className="font-bold">Booking summary</h2><div className="my-4 flex gap-3"><img src={demoBooking.movie.poster} className="h-24 w-16 rounded-2xl object-cover"/><div><b>{demoBooking.movie.title}</b><p className="text-sm text-muted">{demoBooking.cinema.name}</p><p className="text-sm text-muted">Seats {demoBooking.seats.map(s=>s.id).join(', ')}</p></div></div><Line k="Tickets" v={money(demoBooking.total)}/><Line k="Food" v={money(foodTotal)}/><Line k="Tax" v={money(tax)}/><div className="my-4 border-t border-white/10"/><Line k="Total" v={money(total)} strong/><Link to="/confirmation" className="mt-5 block rounded-2xl bg-ember-gradient py-4 text-center font-bold shadow-glow">Confirm Booking</Link></aside></div>}
function Card({brand,last,active=false}:{brand:string;last:string;active?:boolean}){return <div className={`rounded-3xl border p-4 ${active?'border-ember bg-ember-gradient':'border-white/10 bg-white/5'}`}><div className="flex justify-between"><b>{brand}</b>{active&&<span className="text-xs"><Check size={14} className="inline"/> DEFAULT</span>}</div><p className="mt-4">**** **** **** {last}</p><div className="mt-4 flex justify-between text-xs"><span>Card Holder<br/>Mohamed</span><Wifi/></div></div>}
function Line({k,v,strong=false}:{k:string;v:string;strong?:boolean}){return <div className={`flex justify-between py-2 ${strong?'text-xl font-bold':'text-sm text-muted'}`}><span>{k}</span><span>{v}</span></div>}
export function ConfirmationPage(){return <div className="py-8 text-center"><div className="mx-auto mb-5 grid h-24 w-24 place-items-center rounded-full border border-ember text-ember"><Check size={44}/></div><h1 className="text-3xl font-bold">Booking Confirmed!</h1><p className="mt-2 text-muted">Your tickets have been booked successfully.</p><div className="mt-6"><TicketCard/></div><div className="mx-auto mt-5 grid max-w-md gap-3"><Link to="/tickets" className="rounded-2xl bg-ember-gradient py-4 font-bold">View Tickets</Link><Link to="/" className="rounded-2xl bg-white/10 py-4 font-bold">Back To Home</Link></div></div>}
