import type { Booking, Cinema, FoodItem, Movie, Seat, Show } from './types/domain';

export const movies: Movie[] = [
  {
    id: 'f1-the-movie',
    title: 'F1: The Movie',
    status: 'NOW_SHOWING',
    genre: 'Sports, Action, Drama',
    language: 'English',
    rating: 8.2,
    duration: '2h 35m',
    ageRating: 'PG-13',
    poster: '/movie-art/f1-poster.svg',
    banner: '/movie-art/f1-banner.svg',
    synopsis: 'A retired Formula One driver returns to mentor a rookie prodigy as their team chases one last podium under the floodlights.',
    trailerUrl: 'https://www.youtube.com/watch?v=CT2_P2DZBR0',
    cast: ['Brad Pitt', 'Damson Idris', 'Kerry Condon', 'Javier Bardem'],
  },
  {
    id: 'superman-skybound',
    title: 'Superman: Skybound',
    status: 'NOW_SHOWING',
    genre: 'Superhero, Action, Hopepunk',
    language: 'English',
    rating: 8.4,
    duration: '2h 18m',
    ageRating: 'PG-13',
    poster: 'https://images.unsplash.com/photo-1516849841032-87cbac4d88f7?auto=format&fit=crop&w=600&q=80',
    banner: 'https://images.unsplash.com/photo-1517976487492-576ea6b2936d?auto=format&fit=crop&w=1600&q=80',
    synopsis: 'A solar-powered guardian returns to Metropolis for a sky-splitting rescue mission that tests courage, identity, and hope.',
    trailerUrl: '#',
    cast: ['Clark Kent', 'Lois Lane', 'Mister Terrific', 'Lex Luthor'],
  },
  {
    id: 'spider-man-neon-web',
    title: 'Spider-Man: Neon Web',
    status: 'NOW_SHOWING',
    genre: 'Superhero, Animation, Multiverse',
    language: 'English',
    rating: 9.1,
    duration: '2h 09m',
    ageRating: 'PG',
    poster: 'https://images.unsplash.com/photo-1635805737707-575885ab0820?auto=format&fit=crop&w=600&q=80',
    banner: 'https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=1600&q=80',
    synopsis: 'A neon-lit web slinger jumps between animated city layers to save friends before the multiverse collapses at midnight.',
    trailerUrl: '#',
    cast: ['Miles Morales', 'Gwen Stacy', 'Peter Parker', 'Miguel O’Hara'],
  },
  {
    id: 'iron-man-arc-night',
    title: 'Iron Man: Arc Night',
    status: 'NOW_SHOWING',
    genre: 'Marvel, Tech Thriller, Action',
    language: 'English',
    rating: 8.6,
    duration: '2h 14m',
    ageRating: 'PG-13',
    poster: 'https://images.unsplash.com/photo-1608889825103-eb5ed706fc64?auto=format&fit=crop&w=600&q=80',
    banner: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?auto=format&fit=crop&w=1600&q=80',
    synopsis: 'An armored genius races through an amber city skyline as a rogue reactor threatens every cinema-sized screen in town.',
    trailerUrl: '#',
    cast: ['Tony Stark', 'Pepper Potts', 'Rhodey', 'Friday'],
  },
  {
    id: 'batman-gotham-after-dark',
    title: 'Batman: Gotham After Dark',
    status: 'NOW_SHOWING',
    genre: 'Detective, Noir, Action',
    language: 'English',
    rating: 8.7,
    duration: '2h 32m',
    ageRating: 'PG-13',
    poster: 'https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?auto=format&fit=crop&w=600&q=80',
    banner: 'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=1600&q=80',
    synopsis: 'A masked detective follows orange streetlights and rain-slick clues into Gotham’s deepest midnight mystery.',
    trailerUrl: '#',
    cast: ['Bruce Wayne', 'Selina Kyle', 'Jim Gordon', 'The Riddler'],
  },
  {
    id: 'marvel-secret-cosmos',
    title: 'Marvel: Secret Cosmos',
    status: 'COMING_SOON',
    genre: 'Marvel, Ensemble, Cosmic Action',
    language: 'English',
    rating: 0,
    duration: '2h 28m',
    ageRating: 'PG-13',
    poster: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=600&q=80',
    banner: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?auto=format&fit=crop&w=1600&q=80',
    synopsis: 'Heroes from every corner of the cosmos assemble when a hidden star-gate turns the night sky into a battlefield.',
    trailerUrl: '#',
    cast: ['Captain Marvel', 'Doctor Strange', 'Nova', 'The Guardians'],
  },
  {
    id: 'rover',
    title: 'The Rover',
    status: 'NOW_SHOWING',
    genre: 'Drama, Sci‑Fi, Thriller',
    language: 'English',
    rating: 8.1,
    duration: '1h 52m',
    ageRating: 'R',
    poster: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=600&q=80',
    banner: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=80',
    synopsis: 'A tense desert odyssey about loyalty, survival, and what remains after society falls away.',
    trailerUrl: '#',
    cast: ['Guy Pearce', 'Robert Pattinson', 'Scoot McNairy'],
  },
  {
    id: 'nebula',
    title: 'Nebula Run',
    status: 'COMING_SOON',
    genre: 'Action, Space Opera',
    language: 'English',
    rating: 0,
    duration: '2h 06m',
    ageRating: 'PG-13',
    poster: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=600&q=80',
    banner: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=1600&q=80',
    synopsis: 'A smuggler crew races through a collapsing nebula to save the last passenger colony.',
    trailerUrl: '#',
    cast: ['Aisha Hart', 'Daniel Kaluuya', 'Gemma Chan'],
  },
];

export const cinemas: Cinema[] = [
  { id: 'cairo-festival', name: 'Cairo Festival City Cinema', distance: '3.2 km', rating: 4.6, address: 'Festival Avenue, Screen 5', premium: true },
  { id: 'citystars', name: 'Citystars Cinema', distance: '5.6 km', rating: 4.8, address: 'Omar Ibn El Khattab, Screen 2', premium: true },
  { id: 'mall-arabia', name: 'Mall of Arabia Cinema', distance: '7.8 km', rating: 4.5, address: 'Gate 9, Premium Hall', premium: false },
  { id: 'gotham-imax', name: 'Gotham IMAX Opera', distance: '9.1 km', rating: 4.9, address: 'Noir Avenue, Hall Zero', premium: true },
];

export const shows: Show[] = [
  { id: 'show-1', movieId: 'f1-the-movie', cinemaId: 'cairo-festival', hall: 'Screen 5', date: '2026-05-23', time: '8:30 PM', basePrice: 28, occupancy: 76 },
  { id: 'show-2', movieId: 'f1-the-movie', cinemaId: 'citystars', hall: 'Screen 2', date: '2026-05-24', time: '10:45 PM', basePrice: 30, occupancy: 68 },
  { id: 'show-3', movieId: 'rover', cinemaId: 'mall-arabia', hall: 'Screen 8', date: '2026-05-25', time: '12:30 PM', basePrice: 18, occupancy: 51 },
  { id: 'show-4', movieId: 'superman-skybound', cinemaId: 'cairo-festival', hall: 'Sky Hall', date: '2026-05-23', time: '6:30 PM', basePrice: 25, occupancy: 69 },
  { id: 'show-5', movieId: 'superman-skybound', cinemaId: 'gotham-imax', hall: 'IMAX 1', date: '2026-05-24', time: '9:45 PM', basePrice: 31, occupancy: 78 },
  { id: 'show-6', movieId: 'spider-man-neon-web', cinemaId: 'citystars', hall: 'Animation Dome', date: '2026-05-23', time: '5:10 PM', basePrice: 22, occupancy: 83 },
  { id: 'show-7', movieId: 'spider-man-neon-web', cinemaId: 'mall-arabia', hall: 'Screen 4', date: '2026-05-25', time: '8:20 PM', basePrice: 21, occupancy: 57 },
  { id: 'show-8', movieId: 'iron-man-arc-night', cinemaId: 'cairo-festival', hall: 'Arc Reactor Hall', date: '2026-05-24', time: '7:20 PM', basePrice: 29, occupancy: 74 },
  { id: 'show-9', movieId: 'batman-gotham-after-dark', cinemaId: 'gotham-imax', hall: 'Noir Screen', date: '2026-05-23', time: '11:00 PM', basePrice: 30, occupancy: 88 },
  { id: 'show-10', movieId: 'marvel-secret-cosmos', cinemaId: 'citystars', hall: 'Galaxy Hall', date: '2026-06-02', time: '8:00 PM', basePrice: 28, occupancy: 42 },
];

export const seats: Seat[] = Array.from({ length: 8 }).flatMap((_, rowIndex) =>
  Array.from({ length: 10 }).map((__, seatIndex) => {
    const row = String.fromCharCode(65 + rowIndex);
    const id = `${row}${seatIndex + 1}`;
    return {
      id,
      row,
      number: seatIndex + 1,
      type: rowIndex > 5 ? 'VIP' : rowIndex > 2 ? 'PREMIUM' : 'STANDARD',
      price: rowIndex > 5 ? 34 : rowIndex > 2 ? 28 : 22,
      state: (['A6', 'C9', 'C10', 'D5', 'D6', 'D10'].includes(id) ? 'booked' : 'available') as const,
    };
  }),
);

export const food: FoodItem[] = [
  { id: 'combo-1', category: 'Combos', name: 'Amber Couple Combo', price: 18, image: 'https://images.unsplash.com/photo-1585647347483-22b66260dfff?auto=format&fit=crop&w=400&q=80', stock: 32, combo: true },
  { id: 'popcorn', category: 'Snacks', name: 'Truffle Popcorn', price: 9, image: 'https://images.unsplash.com/photo-1578849278619-e73505e9610f?auto=format&fit=crop&w=400&q=80', stock: 120, combo: false },
  { id: 'mocha', category: 'Drinks', name: 'Iced Cinema Mocha', price: 7, image: 'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=400&q=80', stock: 85, combo: false },
];

export const demoBooking: Booking = {
  id: 'BK45',
  movie: movies[0],
  cinema: cinemas[0],
  show: shows[0],
  seats: seats.filter((seat) => ['A5', 'C6', 'F7'].includes(seat.id)).map((seat) => ({ ...seat, state: 'selected' })),
  total: 78,
  status: 'CONFIRMED',
  qrCode: 'BK45-F1-2026-05-23-A5-C6-F7',
};
