import type { Booking, Cinema, FoodItem, Movie, Seat, Show } from './types/domain';

export const movies: Movie[] = [
  {
    id: 'dune-2',
    title: 'Dune: Part Two',
    status: 'NOW_SHOWING',
    genre: 'Sci-Fi, Adventure, Drama',
    language: 'English',
    rating: 8.8,
    duration: '2h 46m',
    ageRating: 'PG-13',
    poster: '/movie-art/dune-poster.svg',
    banner: '/movie-art/dune-banner.svg',
    synopsis: 'Paul Atreides unites with CHANI and the Fremen while seeking revenge against the Conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the universe, he must prevent a terrible future only he can foresee.',
    trailerUrl: '#',
    cast: ['Timothée Chalamet', 'Zendaya', 'Rebecca Ferguson', 'Javier Bardem'],
  },
  {
    id: 'godzilla-kong',
    title: 'Godzilla x Kong',
    status: 'NOW_SHOWING',
    genre: 'Action, Adventure',
    language: 'English',
    rating: 8.4,
    duration: '2h',
    ageRating: 'PG-13',
    poster: 'https://images.unsplash.com/photo-1546182990-dffeafbe841d?auto=format&fit=crop&w=600&q=80',
    banner: 'https://images.unsplash.com/photo-1546182990-dffeafbe841d?auto=format&fit=crop&w=1600&q=80',
    synopsis: 'Two legendary titans collide when a hidden threat rises from below the earth.',
    trailerUrl: '#',
    cast: ['Rebecca Hall', 'Brian Tyree Henry', 'Dan Stevens'],
  },
  {
    id: 'apes-kingdom',
    title: 'Kingdom of the Planet of the Apes',
    status: 'NOW_SHOWING',
    genre: 'Sci-Fi, Action',
    language: 'English',
    rating: 8.1,
    duration: '2h 25m',
    ageRating: 'PG-13',
    poster: 'https://images.unsplash.com/photo-1605648916361-9bc12ad6a569?auto=format&fit=crop&w=600&q=80',
    banner: 'https://images.unsplash.com/photo-1605648916361-9bc12ad6a569?auto=format&fit=crop&w=1600&q=80',
    synopsis: 'A young ape questions an empire built on myth and searches for the truth.',
    trailerUrl: '#',
    cast: ['Owen Teague', 'Freya Allan', 'Kevin Durand'],
  },
  {
    id: 'oppenheimer',
    title: 'Oppenheimer',
    status: 'NOW_SHOWING',
    genre: 'Biography, Drama',
    language: 'English',
    rating: 8.5,
    duration: '3h',
    ageRating: 'R',
    poster: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?auto=format&fit=crop&w=600&q=80',
    banner: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?auto=format&fit=crop&w=1600&q=80',
    synopsis: 'A brilliant physicist changes history and wrestles with the cost of creation.',
    trailerUrl: '#',
    cast: ['Cillian Murphy', 'Emily Blunt', 'Robert Downey Jr.'],
  },
  {
    id: 'fall-guy',
    title: 'The Fall Guy',
    status: 'NOW_SHOWING',
    genre: 'Action, Adventure',
    language: 'English',
    rating: 6.5,
    duration: '2h',
    ageRating: 'PG-13',
    poster: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=600&q=80',
    banner: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=80',
    synopsis: 'A stuntman returns to set and lands in the middle of a real mystery.',
    trailerUrl: '#',
    cast: ['Ryan Gosling', 'Emily Blunt', 'Aaron Taylor-Johnson'],
  },
  {
    id: 'furiosa',
    title: 'Furiosa: A Mad Max Saga',
    status: 'NOW_SHOWING',
    genre: 'Action, Adventure',
    language: 'English',
    rating: 7.6,
    duration: '2h 28m',
    ageRating: 'R',
    poster: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=600&q=70',
    banner: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=70',
    synopsis: 'A warrior survives the wasteland and begins a road toward revenge.',
    trailerUrl: '#',
    cast: ['Anya Taylor-Joy', 'Chris Hemsworth', 'Tom Burke'],
  },
  {
    id: 'beekeeper',
    title: 'The Beekeeper',
    status: 'NOW_SHOWING',
    genre: 'Action, Thriller',
    language: 'English',
    rating: 6.8,
    duration: '1h 45m',
    ageRating: 'R',
    poster: 'https://images.unsplash.com/photo-1504198322253-cfa87a0ff25f?auto=format&fit=crop&w=600&q=80',
    banner: 'https://images.unsplash.com/photo-1504198322253-cfa87a0ff25f?auto=format&fit=crop&w=1600&q=80',
    synopsis: 'A quiet keeper uncovers a conspiracy and goes after everyone responsible.',
    trailerUrl: '#',
    cast: ['Jason Statham', 'Emmy Raver-Lampman', 'Josh Hutcherson'],
  },
  {
    id: 'rover',
    title: 'The Rover',
    status: 'COMING_SOON',
    genre: 'Drama, Sci-Fi, Thriller',
    language: 'English',
    rating: 8.1,
    duration: '1h 52m',
    ageRating: 'R',
    poster: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=600&q=80',
    banner: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=80',
    synopsis: 'A tense desert odyssey about loyalty, survival, and what remains after society falls away.',
    trailerUrl: '#',
    cast: ['Guy Pearce', 'Robert Pattinson', 'Scoot McNairy'],
  },
];

export const cinemas: Cinema[] = [
  { id: 'cairo-festival', name: 'Cairo Festival City Cinema', distance: '3.2 km', rating: 4.6, address: '3.2 km • 2.7k reviews', premium: true },
  { id: 'citystars', name: 'Citystars Cinema', distance: '5.6 km', rating: 4.8, address: '5.6 km • 3.1k reviews', premium: true },
  { id: 'mall-arabia', name: 'Mall of Arabia Cinema', distance: '7.8 km', rating: 4.5, address: '7.8 km • 1.9k reviews', premium: false },
  { id: 'point-90', name: 'Point 90 Cinema', distance: '9.3 km', rating: 4.4, address: '9.3 km • 2.2k reviews', premium: true },
];

export const shows: Show[] = [
  { id: 'show-1', movieId: 'dune-2', cinemaId: 'cairo-festival', hall: 'JCX Cinema 25', date: '2024-05-24', time: '07:45 PM', basePrice: 24, occupancy: 72 },
  { id: 'show-2', movieId: 'dune-2', cinemaId: 'citystars', hall: 'Screen 4', date: '2024-05-24', time: '08:30 PM', basePrice: 26, occupancy: 64 },
  { id: 'show-3', movieId: 'rover', cinemaId: 'mall-arabia', hall: 'Screen 2', date: '2024-05-31', time: '06:30 PM', basePrice: 18, occupancy: 51 },
  { id: 'show-4', movieId: 'godzilla-kong', cinemaId: 'cairo-festival', hall: 'Sky Hall', date: '2024-05-24', time: '6:30 PM', basePrice: 25, occupancy: 69 },
  { id: 'show-5', movieId: 'apes-kingdom', cinemaId: 'citystars', hall: 'IMAX 1', date: '2024-05-24', time: '9:45 PM', basePrice: 31, occupancy: 78 },
  { id: 'show-6', movieId: 'oppenheimer', cinemaId: 'citystars', hall: 'Animation Dome', date: '2024-05-23', time: '5:10 PM', basePrice: 22, occupancy: 83 },
  { id: 'show-7', movieId: 'fall-guy', cinemaId: 'mall-arabia', hall: 'Screen 4', date: '2024-05-25', time: '8:20 PM', basePrice: 21, occupancy: 57 },
  { id: 'show-8', movieId: 'furiosa', cinemaId: 'cairo-festival', hall: 'Arc Reactor Hall', date: '2024-05-24', time: '7:20 PM', basePrice: 29, occupancy: 74 },
  { id: 'show-9', movieId: 'beekeeper', cinemaId: 'point-90', hall: 'Noir Screen', date: '2024-05-23', time: '11:00 PM', basePrice: 30, occupancy: 88 },
];

export const seats: Seat[] = Array.from({ length: 8 }).flatMap((_, rowIndex) =>
  Array.from({ length: 10 }).map((__, seatIndex) => {
    const row = String.fromCharCode(65 + rowIndex);
    const id = `${row}${seatIndex + 1}`;
    return { id, row, number: seatIndex + 1, type: rowIndex > 5 ? 'VIP' : rowIndex > 2 ? 'PREMIUM' : 'STANDARD', price: rowIndex > 5 ? 34 : rowIndex > 2 ? 28 : 22, state: (['A6', 'C9', 'C10', 'D5', 'D6', 'D10'].includes(id) ? 'booked' : 'available') as const };
  }),
);

export const food: FoodItem[] = [
  { id: 'combo-1', category: 'Combos', name: 'Amber Couple Combo', price: 18, image: 'https://images.unsplash.com/photo-1585647347483-22b66260dfff?auto=format&fit=crop&w=400&q=80', stock: 32, combo: true },
  { id: 'popcorn', category: 'Snacks', name: 'Truffle Popcorn', price: 9, image: 'https://images.unsplash.com/photo-1578849278619-e73505e9610f?auto=format&fit=crop&w=400&q=80', stock: 120, combo: false },
  { id: 'mocha', category: 'Drinks', name: 'Iced Cinema Mocha', price: 7, image: 'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=400&q=80', stock: 85, combo: false },
];

export const demoBooking: Booking = {
  id: 'BK45',
  movie: movies[0],
  cinema: cinemas[0],
  show: shows[0],
  seats: seats.filter((seat) => ['A5', 'C6', 'F7'].includes(seat.id)).map((seat) => ({ ...seat, state: 'selected' })),
  total: 72,
  status: 'CONFIRMED',
  qrCode: 'BK45-DUNE-2024-05-24-14-15',
};
